### ISSUE TITLE
Se puede traer la configuracion directamente a menos q querias personalizar

### ISSUE THREAD

**Issue by Shadowrunner11** [POSTPUNK-TELETUBIES/ETL#2]
https://github.com/POSTPUNK-TELETUBIES/ETL/blob/69d537991e3fdcde28da21cabf9c9a048006dde9/apps/web/src/services/EnvService.ts#L1

```ts
import 'dotenv/config'
```

**Comment by lgcarlinf** [comment]
se corrige issue https://github.com/POSTPUNK-TELETUBIES/ETL/pull/3

**Comment by lgcarlinf** [comment]
se corrige con PR https://github.com/POSTPUNK-TELETUBIES/ETL/pull/3
